inventory: 16_3_inventory.o readline.o
	gcc -o inventory 16_3_inventory.o readline.o
16_3_inventory.o: 16_3_inventory.c readline.h
	gcc -c 16_3_inventory.c
readline.o: readline.c readline.h
	gcc -c readline.c